export const productActionsTypes = {
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PROCUCT_FAILED: "GET_PROCUCT_FAILED",

  GET_DETAIL_PRODUCT_REQUEST: "GET_DETAIL_PRODUCT_REQUEST",
  GET_DETAIL_PRODUCT_SUCCESS: "GET_DETAIL_PRODUCT_SUCCESS",
  GET_DETAIL_PROCUCT_FAILED: "GET_DETAIL_PROCUCT_FAILED",
};
